# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5099cfe2b4063610ec5274362eb576f7861e616411cc626ef5eba72ccb4589acf4694f25315139801274d920a4f3c7965b07c5127f85f5a5a4f6a9495772b9af

test:
  secret_key_base: ac009ea2eb9b1659d39684367cbcd140a3f7654f7d887eaff9320c4b408b5772b0904ec785217b39f6ddbbb02261e2bd9070ff1e90db0f6409f7a6a0335510ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
